services:
  app:
    container_name: vidyasetu
    build:
      context: .
      dockerfile: Dockerfile
    # Define variable
    environment:
      - WORKERS=1
    ports:
      - "8127:8000"
    env_file:
      - ./.env
    restart: always

  chromadb:
    container_name: vidyasetu-chromadb
    image: chromadb/chroma:latest
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - PERSIST_DIRECTORY=/chroma/chroma
      - CHROMA_SERVER_ALLOW_RESET=true
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"] 
    volumes:
      - chroma-data:/chroma/chroma
    restart: always

volumes:
  chroma-data:
    driver: local
